[package]
name = "nyx-space"
version = "0.0.3"
authors = ["Christopher Rabotin <christopher.rabotin@gmail.com>"]
description = "A high-fidelity space mission toolkit, with orbit propagation, estimation and some systems engineering"
homepage = "https://github.com/ChristopherRabotin/nyx"
documentation = "https://docs.rs/nyx-space/"
repository = "https://github.com/ChristopherRabotin/nyx"
keywords = ["space", "mission", "design", "orbit", "propagator"]
categories = ["science", "simulation"]
readme = "README.md"
license = "Apache-2.0"
exclude = ["tests/GMAT_scripts/GMAT_V&V_ProcessAndResults.pdf"]

[badges]
maintenance = { status = "actively-developed" }
travis-ci = { repository = "ChristopherRabotin/nyx", branch = "master" }

[dependencies]
nalgebra = "0.14.0"
log = "0.4"
hifitime = "0.1.3"
flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }

[dev-dependencies]
pretty_env_logger = "0.2"

[features]
default = []
unvalidated = [] # Enable to run unvalidated parts of the code
