[package]
name = "nyx-space"
version = "0.0.1"
authors = ["Christopher Rabotin <christopher.rabotin@gmail.com>"]
description = "A high-fidelity space mission toolkit, with orbit propagation, estimation and some systems engineering"
homepage = "https://github.com/ChristopherRabotin/nyx"
documentation = "https://docs.rs/nyx-space/"
repository = "https://github.com/ChristopherRabotin/nyx"
keywords = ["space", "mission", "design", "orbit", "propagator", "integrator", "estimation", "kalman"]
categories = ["science", "simulation"]
readme = "README.md"
license = "Apache-2.0"
exclude = ["tests/GMAT_scripts/GMAT_V&V_ProcessAndResults.pdf"]

[badges]
maintenance = { status = "actively-developed" }
travis-ci = { repository = "ChristopherRabotin/nyx", branch = "master" }

[dependencies]
nalgebra = "0.14.0"
